-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

entity somador16bits is
port (
    a : IN STD_LOGIC_VECTOR (15 downto 0);
    b : IN STD_LOGIC_VECTOR (15 downto 0);
    c : IN STD_LOGIC_VECTOR (15 downto 0);
    d : IN STD_LOGIC_VECTOR (15 downto 0);
    e : IN STD_LOGIC_VECTOR (15 downto 0);
    f : IN STD_LOGIC_VECTOR (15 downto 0);
    g : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    c_out : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of somador16bits is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "somador32bits_somador32bits,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.264000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=110,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal s_a : STD_LOGIC_VECTOR (18 downto 0);
    signal s_b : STD_LOGIC_VECTOR (18 downto 0);
    signal s_c : STD_LOGIC_VECTOR (18 downto 0);
    signal s_d : STD_LOGIC_VECTOR (18 downto 0);
    signal s_e : STD_LOGIC_VECTOR (18 downto 0);
    signal s_f : STD_LOGIC_VECTOR (18 downto 0);
    signal s_g : STD_LOGIC_VECTOR (18 downto 0);
    signal s_c_d : STD_LOGIC_VECTOR (18 downto 0);
    signal s_e_f : STD_LOGIC_VECTOR (18 downto 0);
    signal s_c_d_e_f : STD_LOGIC_VECTOR (18 downto 0);
    signal s_b_a : STD_LOGIC_VECTOR (18 downto 0);
    signal s_c_d_e_f_b_a : STD_LOGIC_VECTOR (18 downto 0);
    signal s_total : STD_LOGIC_VECTOR (18 downto 0);


begin

    s_a <= "000" & a;
    s_b <= "000" & b;
    s_c <= "000" & c;
    s_d <= "000" & d;
    s_e <= "000" & e;
    s_f <= "000" & f;
    s_g <= "000" & g;
    s_c_d <= s_c + s_d;
    s_e_f <= s_e + s_f;
    s_c_d_e_f <= s_c_d + s_e_f;
    s_b_a <= s_b + s_a;
    s_c_d_e_f_b_a <= s_c_d_e_f + s_b_a;
    s_total <= s_c_d_e_f_b_a + s_g;
    ap_return <= s_total(15 downto 0);
    c_out <= s_total(18 downto 16);
end behav;
