-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;

entity somador32bits is
port (
    a : IN STD_LOGIC_VECTOR (15 downto 0);
    b : IN STD_LOGIC_VECTOR (15 downto 0);
    c : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    c_out : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of somador32bits is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "somador32bits_somador32bits,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.064000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=32,HLS_VERSION=2025_1}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal s_a : STD_LOGIC_VECTOR (17 downto 0);
    signal s_b : STD_LOGIC_VECTOR (17 downto 0);
    signal s_c : STD_LOGIC_VECTOR (17 downto 0);
    signal s_a_c : STD_LOGIC_VECTOR (17 downto 0);
    signal s_a_c_b : STD_LOGIC_VECTOR (17 downto 0);


begin

    s_a <= "00" & a;
    s_c <= "00" & c;
    s_b <= "00" & b;
    s_a_c <= s_a + s_c;
    s_a_c_b <= s_a_c + s_b;
    ap_return <= s_a_c_b(15 downto 0);
    c_out <= s_a_c_b(17 downto 16);
end behav;
